In [205]:
import pandas as pd
import numpy as np
import plotly.express as px

In [206]:
df = pd.read_csv('diabetes_data_upload.csv')


In [207]:
df.head()

Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0   40   Male       No        Yes                 No      Yes         No   
1   58   Male       No         No                 No      Yes         No   
2   41   Male      Yes         No                 No      Yes        Yes   
3   45   Male       No         No                Yes      Yes        Yes   
4   60   Male      Yes        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      Yes     Yes  Positive  
1             Yes               No      Yes      No  Positive  
2              No              Yes      Yes      No  Positive  
3              No               No       No      No  Positive  
4             Yes              Yes      Yes     Yes  Positive

In [208]:
results = []
for col in df.columns:
    missing_or_not = df[col].isnull().values.any()
    print(col + ' ' + str(missing_or_not))

Age False
Gender False
Polyuria False
Polydipsia False
sudden weight loss False
weakness False
Polyphagia False
Genital thrush False
visual blurring False
Itching False
Irritability False
delayed healing False
partial paresis False
muscle stiffness False
Alopecia False
Obesity False
class False


In [209]:
def convert(x):
    if x == 'Yes' or x == 'Male' or x == 'Positive':
        return 1
    else:
        return 0

In [210]:
df['Gender'].apply(convert)

0      1
1      1
2      1
3      1
4      1
      ..
515    0
516    0
517    0
518    0
519    1
Name: Gender, Length: 520, dtype: int64

In [211]:
df['Gender']

0        Male
1        Male
2        Male
3        Male
4        Male
        ...  
515    Female
516    Female
517    Female
518    Female
519      Male
Name: Gender, Length: 520, dtype: object

In [212]:
for col in df.columns:
    if col != 'Age':
        df[col] = df[col].apply(convert)

In [213]:
Drop_Columns = ['class', 'Age', 'weakness', 'Genital thrush', 'Itching', 'delayed healing', 'muscle stiffness', 'Obesity']
x = df.drop(Drop_Columns,axis=1)
y = df['class']


In [214]:
import sklearn
from sklearn.model_selection import train_test_split

x_train, x_test ,y_train, y_test = train_test_split(x, y)

In [215]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(390, 9)
(130, 9)
(390,)
(130,)


In [216]:
x_test.head()

Gender  Polyuria  Polydipsia  sudden weight loss  Polyphagia  \
177       0         1           1                   1           1   
343       0         0           0                   1           1   
401       1         0           0                   0           0   
64        0         0           0                   0           0   
120       1         1           1                   0           1   

     visual blurring  Irritability  partial paresis  Alopecia  
177                0             0                1         0  
343                0             0                0         0  
401                0             0                0         0  
64                 1             0                1         0  
120                0             0                0         1

In [217]:
 y_train.head()

26     1
272    0
487    1
179    1
67     1
Name: class, dtype: int64

In [218]:
y_test.head

<bound method NDFrame.head of 177    1
343    1
401    0
64     1
120    1
      ..
74     1
290    0
398    0
461    0
104    1
Name: class, Length: 130, dtype: int64>

In [232]:
#Decision tress: Decision Trees are a non-parametric supervised learning method used for classification and regression. The model can predict the value of a target variable by learning simple rules. The more data, the more complex the decision rules and the fitter the model.
from sklearn import tree
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix

parameters = {'criterion' :('gini', 'entropy', 'log_loss'), 'splitter' :('best', 'random')}



In [233]:
total_squared_error = (np.sum((y_test - y_hat)**2)) #get the sum of all the errors (error = what we want (y_test) - what we predicted (y_hat))
mean_squared_error = total_squared_error/len(y_test) #divide this by how many rows/observations we have 
print(mean_squared_error)

0.015384615384615385


In [234]:
clf = GridSearchCV(tree.DecisionTreeClassifier(), parameters)
clf.fit(x_train, y_train)


GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ('gini', 'entropy', 'log_loss'),
                         'splitter': ('best', 'random')})

In [235]:
clf.best_params_


{'criterion': 'entropy', 'splitter': 'random'}

In [236]:
y_hat = clf.predict(x_test)
y_hat


array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1])

In [237]:
fig = px.imshow(confusion_matrix(y_test, y_hat), text_auto=True)

fig.write_html("DecisionTrees.html")
fig.show()


In [225]:
def convert(x):
    if x == 'Yes'or x == 'Male':
        return 1
    else:
        return 0
convert('Female')



0

In [226]:
import numpy as np

def convert(x):
    if x == 'Yes'or x == 'Male':
        return 1
    else:
        return 0
convert('No')

my_list = [x]
my_array = np.array(my_list)
# printing the type of my_array
print(my_array)

[[[1 0 1 ... 0 0 1]
  [1 0 0 ... 0 1 1]
  [1 1 0 ... 0 0 1]
  ...
  [0 1 1 ... 0 1 0]
  [0 0 0 ... 0 0 1]
  [1 0 0 ... 0 0 0]]]


In [227]:
# Plug in converted values into our best ml model, aka decision tree


In [238]:
features = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0]])
def predict(x):
    prediction = clf.predict(x)
    if prediction == 1:
        print('You have Diabetes. Please seek medical attention from a professional')
    if features == np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0]]):
        print('You do not have diabetes. I hope you still enjoyed our project :)')
    if features == np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1]]):
        print('You have Diabetes. Please seek medical attention from a professional')
    else:
        print('You do not have diabetes. I hope you still enjoyed our project :)')

In [239]:
predict(features)


You have Diabetes. Please seek medical attention from a professional


/projects/b36ed0b0-d7f5-416a-895a-d63c582b0b71/miniconda3/envs/ds_env/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning:

X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names



ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [230]:
df.tail()

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
515   39       0         1           1                   1         0   
516   48       0         1           1                   1         1   
517   58       0         1           1                   1         1   
518   32       0         0           0                   0         1   
519   42       1         0           0                   0         0   

     Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
515           1               0                0        1             0   
516           1               0                0        1             1   
517           1               0                1        0             0   
518           0               0                1        1             0   
519           0               0                0        0             0   

     delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
515                1                1                 0         0        0   
516                1                1                 0         0        0   
517                0                1                 1         0        1   
518                1                0                 0         1        0   
519                0                0                 0         0        0   

     class  
515      1  
516      1  
517      1  
518      0  
519      0

In [285]:
Gender = str(input('Gender: '))
Polyuria = str(input('Polyuria: '))
Polydipsia = str(input('Polydipsia: '))
sudden_weight_loss = str(input('Sudden Weight Loss: '))
Polyphagia = str(input('Polyphagia: '))
Visual_Blurring = str(input('Visual Blurring: '))
Irritability = str(input('Irritability: '))
Partial_Paresis = str(input('Partial Paresis: '))
Alopecia = str(input('Alopecia: '))


print(Gender, Polyuria, Polydipsia,  sudden_weight_loss, Polyphagia, Visual_Blurring, Irritability, Partial_Paresis, Alopecia)

Gender:  Male

Polyuria:  Yes

Polydipsia:  No

Sudden Weight Loss:  Yes

Polyphagia:  No

Visual Blurring:  Yes

Irritability:  Yes

Partial Paresis:  No

Alopecia:  Yes

Male Yes No Yes No Yes Yes No Yes


In [297]:
def convert(x):
    if x == 'Yes'or x == 'Male':
        return 1
    else:
        return 0
Gender1 = (convert(Gender))
Polyuria1 = (convert(Polyuria))
Polydipsia1 = (convert(Polydipsia))
SWL = (convert(sudden_weight_loss))
Polyp = (convert(Polyphagia))
VisualB = (convert(Visual_Blurring))
Irrita = (convert(Irritability))
PP = (convert(Partial_Paresis))
Alo = (convert(Alopecia))

Features = np.array([Gender1, Polyuria1, Polydipsia1, SWL, Polyp, VisualB, Irrita, PP, Alo])
Features



array([1, 1, 0, 1, 0, 1, 1, 0, 1])

In [298]:
features = Features
def predict(x):
    prediction = clf.predict(x)
    if prediction == 1:
        print('You have Diabetes. Please seek medical attention from a professional')
    if features == np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0]]):
        print('You do not have diabetes. I hope you still enjoyed our project :)')
    if features == np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1]]):
        print('You have Diabetes. Please seek medical attention from a professional')
    else:
        print('You do not have diabetes. I hope you still enjoyed our project :')
        
        


In [295]:
predict(features)

/projects/b36ed0b0-d7f5-416a-895a-d63c582b0b71/miniconda3/envs/ds_env/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning:

X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names



ValueError: Expected 2D array, got 1D array instead:
array=[1. 1. 0. 1. 0. 1. 1. 0. 1.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.